#!/bin/bash

export PIP=$(which pip pip3 | head -1)

if [[ -n "${PIP:-}" ]]; then
    if which sudo > /dev/null; then
        sudo $PIP install awscli --upgrade
    else
        # This installs the AWS CLI to ~/.local/bin. Make sure that ~/.local/bin is in your $PATH.
        $PIP install awscli --upgrade --user
    fi
elif [[ $(which unzip curl | wc -l) -eq 2 ]]; then
    cd
    curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
    unzip -q awscli-bundle.zip
    if which sudo > /dev/null; then
        sudo ~/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
    else
        awscli-bundle/install -b ~/bin/aws
    fi
    rm -rf awscli-bundle*
    cd -
else
    echo "Unable to install AWS CLI."
    exit 1
fi

if env -u AWS_PROFILE aws --version &> grep -q "aws-cli/1"; then
    echo "AWS CLI V1 has been installed successfully"
    exit 0
else
    echo "There was an issue installing the AWS CLI V1. Exiting."
    exit 1
fi
