#!/bin/bash

echo "== Terraform =="
echo "$(terraform version)"
echo "== Terragrunt =="
echo "$(terragrunt -v)"
echo "==============="
echo "== AWS-CLI =="
echo "$(aws --version)"
echo "============="
echo "== curl =="
echo "$(curl --version)"
echo "=========="
echo "== kubectl =="
echo "$(kubectl version --client)"
echo "============="
echo "== helm =="
echo "$(helm version)"
echo "=========="
echo "== jq =="
echo "$(jq --version)"
echo "========"

ls -la
